#!/usr/bin/env nu
# Preserve all height_test.rs cases, including the expanded nested table macros.
use upstream-literals.nu expected-lines
use import-transform-tests.nu translate

def main [upstream: path, --output: path] {
  let project = ($env.CURRENT_FILE | path dirname | path dirname)
  let output = if $output == null { $project | path join upstream_height_test.mbt } else { $output | path expand }
  let relative = 'tabled/tests/settings/height_test.rs'
  let source = (open --raw ($upstream | path expand | path join $relative))
  let pattern = '(?s)test_table!\(\s*(?<name>\w+),\s*(?<expression>.*?)\s*,\s*(?<expected>(?:"(?:\\.|[^"\\])*"\s*)+)\s*\);'
  let cases = ($source | parse --regex $pattern)
  let count = ($source | parse --regex 'test_table!\(' | length)
  if ($cases | length) != $count {
    error make {msg: $'Failed to extract every case from ($relative)'}
  }
  let body = ($cases | each {|case|
    let expression = ($case.expression
      | str replace --all 'Columns::new(..)' 'Columns::all()'
      | str replace --all 'format!("xxxx\n{s}xxxx\nxxxx\n")' '("xxxx\n" + s + "xxxx\nxxxx\n")'
      | str replace --all 'Format::content(|s|' 'Format::content(s =>'
      | str replace --all 'tabled::col!["SGML"]' '@tabular.Table::from_rows([["SGML"]])'
      | str replace --all --regex '(?s)tabled::row!\[(.*)\]$' '@tabular.Table::from_rows([[$1.to_string()]])')
    let expression = (translate $expression
      | str replace --all --regex '(?<![\w.])(Height|Format)::' '@tabular.$1::')
    let expected = (expected-lines $case.expected)
    $"///|\n// Upstream: ($relative)::($case.name)
test \"upstream height ($case.name)\" {
  let actual = ($expression).to_string\()
  assert_eq\(actual, ($expected))
}\n"
  } | str join (char nl))
  let marker = '// Generated by scripts/import-height-tests.nu.'
  if ($output | path exists) and not (open --raw $output | str starts-with $marker) {
    error make {msg: $'Refusing to overwrite a file not owned by this generator: ($output)'}
  }
  ($marker + "\n\n" + $body) | save --force $output
  print $'height: ($count) source cases preserved'
}
