#!/usr/bin/env nu
# Generate resizing-priority and measurement references from upstream Rust.

def generate [probe: path, output: path] {
  let priorities = [
    [none 'PriorityNone::new()'] [left 'PriorityLeft::new()'] [right 'PriorityRight::new()']
    [min-left 'PriorityMin::left()'] [min-right 'PriorityMin::right()']
    [max-left 'PriorityMax::left()'] [max-right 'PriorityMax::right()']
  ]
  let inputs = [
    [[0 0 0] [6 3 6]] [[2 2 2] [6 3 6]] [[0 0 0] [0 0 0]]
    [[0 0 0] [2 2 2]] [[0 1 0] [0 4 2]]
  ]
  let traces = ($priorities | each {|p|
    $inputs | enumerate | each {|input|
      let mins = ($input.item.0 | each { into string } | str join ',')
      let widths = ($input.item.1 | each { into string } | str join ',')
      let result = (^$probe priority $p.0 $mins $widths | complete)
      if $result.exit_code != 0 { error make {msg: $result.stderr} }
      let expected = ($result.stdout | lines | into int | to json --raw)
      $"///|\n// Reference: tabled resizing-priority selection, 30 consecutive calls.
test \"priority reference ($p.0) ($input.index)\" {
  assert_eq\(priority_trace\(@tabular.($p.1), ($input.item.0 | to json --raw), ($input.item.1 | to json --raw)), ($expected))
}\n"
    }
  } | flatten | str join (char nl))
  let esc = (char -u '1b')
  let records = [
    []
    [['abcdef' 'x' '12'] ['y' 'ab' 'zzzz']]
    [["a\nb\nc" 'x' ''] ['z' "x\ny" "r\ns\nt\nu"]]
    [["a\r\n" $'($esc)[31m中中($esc)[0m' '👩‍🔬'] ['👍🏿' '🏳️' 'x']]
    [['abcdefghijklmnopqrst' "hidden\nline\nline" 'x'] ['a' 'b' 'c']]
  ]
  let setups = [
    [ascii '']
    [empty 'table.with_(@tabular.Style::empty()) |> ignore']
    [psql 'table.with_(@tabular.Style::psql()) |> ignore']
    [padding 'table.with_(@tabular.Padding::new(2, 3, 1, 2)) |> ignore']
    [margin "table.config.set_margin(2, 3, 4, 5, ' ', ' ', ' ', ' ')"]
    [column-span 'table.modify((0, 0), @tabular.Span::column(2)) |> ignore']
    [row-span 'table.modify((0, 0), @tabular.Span::row(2)) |> ignore']
    [mixed-padding "table.modify((0, 0), @tabular.Padding::new(0, 0, 3, 0)) |> ignore\n  table.modify((0, 1), @tabular.Padding::new(2, 2, 0, 3)) |> ignore"]
  ]
  let measurements = ($records | enumerate | each {|data|
    $setups | each {|setup|
      let input = ($data.item | each {|row| $row | each {|cell| $cell | encode utf-8 | encode hex } | str join ',' } | str join (char nl))
      let result = ($input | ^$probe measurement $setup.0 | complete)
      if $result.exit_code != 0 { error make {msg: $result.stderr} }
      let expected = ($result.stdout | lines | into int | to json --raw)
      $"///|\n// Reference: tabled Measurement implementations for Width and Height.
test \"measurement reference ($data.index) ($setup.0)\" {
  let table = @tabular.Table::from_rows\(($data.item | to json --raw))
  ($setup.1)
  assert_eq\(measure_dimensions\(table), ($expected))
}\n"
    }
  } | flatten | str join (char nl))
  let marker = '// Generated by scripts/import-dimension-reference-tests.nu.'
  if ($output | path exists) and not (open --raw $output | str starts-with $marker) {
    error make {msg: $'Refusing to overwrite a file not owned by this generator: ($output)'}
  }
  ($marker + "\n\n" + $traces + "\n" + $measurements) | save --force $output
  print $'Preserved 35 priority traces and 40 dimension measurement scenarios'
}

def main [upstream: path] {
  let root = ($upstream | path expand)
  let project = ($env.CURRENT_FILE | path dirname | path dirname)
  let scratch = (mktemp --directory)
  try {
    mkdir ($scratch | path join src)
    cp ($project | path join scripts/reference/dimension_probe.rs) ($scratch | path join src/main.rs)
    {
      package: {name: tabular-dimension-probe, version: '0.0.0', edition: '2021'}
      dependencies: {tabled: {path: ($root | path join tabled), default-features: false, features: [std ansi]}}
      patch: {crates-io: {papergrid: {path: ($root | path join papergrid)}}}
    } | to toml | save ($scratch | path join Cargo.toml)
    let result = (^cargo build --manifest-path ($scratch | path join Cargo.toml) | complete)
    if $result.exit_code != 0 { error make {msg: $result.stderr} }
    generate ($scratch | path join target/debug/tabular-dimension-probe) ($project | path join dimension_reference_test.mbt)
  } finally { rm --recursive $scratch }
}
