#!/usr/bin/env nu
# Import unicode-width 0.2.2 metadata and independent reference fixtures.
# This does not modify the Rust source directory or use MoonBit output.
use upstream-literals.nu decode-rust-string

def save-owned [text: string, output: path] {
  let marker = '// Generated by scripts/import-unicode-width.nu.'
  if ($output | path exists) and not (open --raw $output | str starts-with $marker) {
    error make {msg: $'Refusing to overwrite a file not owned by this generator: ($output)'}
  }
  ($marker + "\n" + $text) | save --force $output
}

def generate [source: path, probe: path, output: path] {
  let result = (^$probe ranges | complete)
  if $result.exit_code != 0 { error make {msg: $result.stderr} }
  let ranges = ($result.stdout | lines | split column ' ' start end value | into int start end value)
  let entries = ($ranges | each {|r| $"  \(($r.start), ($r.end), ($r.value))," } | str join (char nl))
  save-owned $"// unicode-width 0.2.2, Unicode 17.0.0. See THIRD_PARTY_NOTICES.md.
// Packed fields: width in bits 0..1, WidthInfo in 2..17, emoji/text/modifier/
// transparent-zero-width flags in bits 18..21. Unlisted scalars have value 1.
\n///|\nlet unicode_width_ranges : FixedArray[\(Int, Int, Int)] = [\n($entries)\n]\n" ($output | path join unicode_data.mbt)

  let raw = (open --raw ($source | path join tests/tests.rs))
  # Keep every literal string from the upstream width assertions. Rust generates
  # expectations, including assertions that also contain CJK-specific arguments.
  let assertions = ($raw | parse --regex '(?:assert_width!\(|assert_eq!\()\s*(?<literal>"(?:\\.|[^"\\])*")'
    | get literal | each {|s| decode-rust-string $s })
  let emojis = (open --raw ($source | path join tests/emoji-test.txt)
    | lines | where {|line| $line =~ '^\s*[0-9A-F]'}
    | each {|line|
      $line | split row ';' | first | str trim | split row --regex '\s+'
      | each {|scalar| char --unicode $scalar } | str join ''
    })
  let cases = ($assertions | append $emojis | uniq)
  let inputs = ($cases | each {|text| $text | encode utf-8 | encode hex } | str join (char nl))
  let result = (($inputs + (char nl)) | ^$probe widths | complete)
  if $result.exit_code != 0 { error make {msg: $result.stderr} }
  let widths = ($result.stdout | lines | into int)
  if ($widths | length) != ($cases | length) { error make {msg: 'Incomplete Unicode reference response'} }
  let checks = ($cases | enumerate | each {|case|
    let input = ($case.item | to json --raw)
    $"  assert_eq\(get_string_width\(($input)), ($widths | get $case.index))"
  } | chunks 100 | enumerate | each {|group|
    $"///|\n// Reference: unicode-width 0.2.2 tests/tests.rs and tests/emoji-test.txt.
test \"Unicode text reference group ($group.index)\" {
($group.item | str join (char nl))
}\n"
  } | str join (char nl))
  save-owned $checks ($output | path join unicode_reference_test.mbt)
  let result = (^$probe scalar-digests | complete)
  if $result.exit_code != 0 { error make {msg: $result.stderr} }
  let digests = ($result.stdout | lines)
  save-owned $"///|\n// Exhaustive independent Rust reference: every valid Unicode scalar.
test \"Unicode scalar width digests\" {
  let mut chars : UInt64 = 14695981039346656037UL
  let mut strings = chars
  for cp in 0..=0x10ffff {
    if cp.to_char\() is Some\(ch) {
      chars = \(chars ^ get_char_width\(ch).to_uint64\()) * 1099511628211UL
      strings = \(strings ^ get_string_width\(ch.to_string\()).to_uint64\()) * 1099511628211UL
    }
  }
  assert_eq\(chars, ($digests.0)UL)
  assert_eq\(strings, ($digests.1)UL)
}\n" ($output | path join unicode_scalar_test.mbt)
  print $'Imported ($ranges | length) Unicode metadata ranges and ($cases | length) reference strings'
}

def main [unicode_width: path, --output: path] {
  let source = ($unicode_width | path expand)
  let manifest = (open ($source | path join Cargo.toml))
  if $manifest.package.version != '0.2.2' { error make {msg: 'Expected unicode-width 0.2.2'} }
  let project = ($env.CURRENT_FILE | path dirname | path dirname)
  let output = if $output == null { $project | path join papergrid } else { $output | path expand }
  let scratch = (mktemp --directory)
  try {
    let table = (open --raw ($source | path join src/tables.rs))
    let export = (open --raw ($project | path join scripts/reference/unicode_metadata.rs))
    ($table + "\n" + $export) | save ($scratch | path join tables.rs)
    cp ($project | path join scripts/reference/unicode_probe.rs) ($scratch | path join main.rs)
    let probe = ($scratch | path join probe)
    let result = (^rustc --edition=2021 ($scratch | path join main.rs) -O -o $probe | complete)
    if $result.exit_code != 0 { error make {msg: $result.stderr} }
    generate $source $probe $output
  } finally {
    rm --recursive $scratch
  }
}
