#!/usr/bin/env nu
# Preserve the five assertion-bearing documentation examples for indent settings.
use upstream-literals.nu decode-rust-string

def main [upstream: path, --output: path] {
  let project = ($env.CURRENT_FILE | path dirname | path dirname)
  let output = if $output == null { $project | path join upstream_indent_docs_test.mbt } else { $output | path expand }
  let cases = [
    {name: padding, code: '@tabular.Table::from_rows([["char"], ["2"], ["0"], ["2"], ["2"]]).with_(@tabular.Style::modern()).modify((2, 0), @tabular.Padding::new(1, 1, 2, 2))'}
    {name: padding_color, code: '@tabular.Table::from_rows([["char"], ["2"], ["0"], ["2"], ["4"]]).with_(@tabular.Style::modern()).modify((2, 0), @tabular.Padding::new(2, 4, 0, 0)).modify((2, 0), @tabular.PaddingColor::filled(@tabular.Color::fg_red()))'}
    {name: padding_expand, code: '@tabular.Table::from_rows([["2", "0", "2", "1"], ["2", "0", "2", "2"], ["2", "0", "2", "3"], ["2", "0", "2", "4"]]).with_(@tabular.Style::ascii()).with_(@tabular.PaddingColor::filled(@tabular.Color::bg_blue())).modify((2, 1), @tabular.Padding::new(2, 2, 3, 3)).with_(@tabular.PaddingExpand::Horizontal).with_(@tabular.PaddingExpand::Vertical)'}
    {name: margin, code: 'upstream_string_table(["Hello", "World", "!"]).with_(@tabular.Style::markdown()).with_(@tabular.Margin::new(left=3, right=3, top=1, bottom=0))'}
    {name: margin_color, code: 'upstream_string_table(["Hello", "World", "!"]).with_(@tabular.Style::markdown()).with_(@tabular.Margin::new(left=3, right=3, top=1, bottom=0)).with_(@tabular.MarginColor::filled(@tabular.Color::bg_red()))'}
  ]
  let body = ($cases | each {|case|
    let relative = $'tabled/src/settings/($case.name)/mod.rs'
    let source = (open --raw ($upstream | path expand | path join $relative)
      | str replace --all --regex '(?m)^/// ?' '')
    let matches = ($source | parse --regex '(?s)assert_eq!\(\s*table(?:\.to_string\(\))?,\s*concat!\((?<literals>(?:\s*"(?:\\.|[^"\\])*",?\s*)+)\)')
    if ($matches | length) != 1 { error make {msg: $'Expected one documentation assertion in ($relative)'} }
    let expected = ($matches.0.literals
      | parse --regex '("(?:\\.|[^"\\])*")'
      | get capture0
      | each {|literal| decode-rust-string $literal }
      | str join ''
      | to json --raw)
    $"///|\n// Upstream documentation: ($relative)
test \"upstream indent documentation ($case.name)\" {
  let table = ($case.code)
  assert_eq\(table.to_string\(), ($expected))
}\n"
  } | str join (char nl))
  let marker = '// Generated by scripts/import-indent-doc-tests.nu.'
  if ($output | path exists) and not (open --raw $output | str starts-with $marker) { error make {msg: 'Output is not owned by this generator'} }
  ($marker + "\n\n" + $body) | save --force $output
  print 'Preserved 5 upstream indent documentation assertions'
}
