#!/usr/bin/env nu
use upstream-probe.nu build-upstream-probe
# Compare rendered output, records, and observable dimension cache with Rust.
use upstream-literals.nu decode-rust-string

def generate [probe: path, output: path] {
  let cases = [list long-list short-list align cell-align settings array nested record-wrap record-increase max min percent percent-increase minimum-priority maximum-priority justify-max justify-min mixed-padding row-span crlf heights height-row-hint height-no-hint color]
  let tests = ($cases | each {|mode|
    let result = (^$probe $mode | complete)
    if $result.exit_code != 0 { error make {msg: $result.stderr} }
    let parts = ($result.stdout | lines)
    if ($parts | length) != 7 { error make {msg: $'Unexpected probe response for ($mode)'} }
    let rendered = (decode-rust-string $parts.0 | to json --raw)
    let records = ($parts | skip 5 | each {|row|
      $row | parse --regex '("(?:\\.|[^"\\])*")' | get capture0 | each {|literal| decode-rust-string $literal }
    } | to json --raw)
    $"///|\n// Reference: tabled width options and CompleteDimension at the pinned source revision.
test \"width state reference ($mode)\" {
  let table = upstream_width_state\(\"($mode)\")
  assert_eq\(table.to_string\(), ($rendered))
  assert_eq\(table.get_dimension\().get_widths\(), ($parts.1))
  assert_eq\(table.get_dimension\().get_heights\(), ($parts.2))
  assert_eq\(table.total_width\(), ($parts.3))
  assert_eq\(table.total_height\(), ($parts.4))
  assert_eq\(table.rows, ($records))
}\n"
  } | str join (char nl))
  let marker = '// Generated by scripts/import-width-state-tests.nu.'
  if ($output | path exists) and not (open --raw $output | str starts-with $marker) { error make {msg: 'Output is not owned by this generator'} }
  ($marker + "\n\n" + $tests) | save --force $output
  print $'Compared ($cases | length) upstream width state scenarios'
}

def main [upstream: path, --probe: path, --output: path] {
  let project = ($env.CURRENT_FILE | path dirname | path dirname)
  let output = if $output == null { $project | path join width_state_reference_test.mbt } else { $output | path expand }
  if $probe != null { generate ($probe | path expand) $output; return }
  let scratch = (mktemp --directory)
  try {
    let binary = (build-upstream-probe $upstream ($project | path join scripts/reference/width_state_probe.rs) $scratch)
    generate $binary $output
  } finally {
    rm --recursive $scratch
  }
}
