#!/usr/bin/env nu
# Port the four upstream data-transform test suites. Requires Nushell 0.115+.
# The expected text comes only from upstream, never from MoonBit render output.

def translate [expression: string]: nothing -> string {
  $expression
  | str trim
  | str replace --all --regex 'Matrix::iter\(\[(.*?)\]\)' {|tuples|
      let rows = ($tuples
        | parse --regex '\((?<values>[\d,\s]+)\)'
        | each {|row| '[' + $row.values + ']' }
        | str join ', ')
      'upstream_int_table([' + $rows + '])'
    }
  | str replace --all --regex 'Matrix::(?:new|table)\(' 'upstream_matrix('
  | str replace --all 'Matrix::empty()' '@tabular.Table::from_rows([])'
  | str replace --all '.to_table()' ''
  | str replace --all --regex '\.insert\(\((\d+),\s*(\d+)\)\.into\(\),\s*("[^"\n]*")\)' '.modify_cell(@tabular.Cell::new($1, $2), @tabular.Setting::format(@tabular.Format::value($3)))'
  | str replace --all ".with(Highlight::new(Rows::one(0)).border(Border::new().top('*')))" '.highlight(upstream_top_border())'
  | str replace --all ".with(Highlight::new(Cell::new(0, 2)).border(Border::new().bottom('*')))" '.highlight(upstream_bottom_border())'
  | str replace --all '.with(Rotate::' '.rotate(Rotate::'
  | str replace --all '.with(Reverse::' '.reverse(Reverse::'
  | str replace --all '.with(Concat::' '.concat(Concat::'
  | str replace --all '.with(Dup::' '.duplicate(Dup::'
  | str replace --all '.with(Style::' '.apply(Style::'
  | str replace --all 'Columns::' 'Cols::'
  | str replace --all 'Rows::new(1..3)' 'Rows::new(1, 3)'
  | str replace --all 'Rows::new(1..)' 'Rows::new(1, -1)'
  | str replace --all --regex '(?<![\w.])(Rotate|Reverse|Offset|Concat|Dup|Style|Rows|Cols|Segment)::' '@tabular.$1::'
  | str replace --all --regex '(?<![\w.])Cell::' '@tabular.Cell::'
  | str replace --all 'let mut ' 'let '
  | str replace --all --regex '(?m)^(\s*table\d\.[^;]+);' '$1 |> ignore'
  | str replace --all ';' ''
}

def expected-value [source: string]: nothing -> string {
  let source = ($source | str trim | str trim --right --char ',')
  if ($source | str starts-with 'Matrix::') {
    '(' + (translate $source) + ').to_string()'
  } else {
    let parts = ($source
      | parse --regex '(?<text>"(?:\\.|[^"\\])*")'
      | get text
      | each { from json })
    let text = ($parts | str join (char nl))
    if $text == '' {
      '""'
    } else {
      "(\n" + ($text | split row (char nl) | each {|line| '    #|' + $line } | str join (char nl)) + "\n  )"
    }
  }
}

# Read the supplied clone and generate MoonBit tests under the project root.
def main [upstream: path, --output: path] {
  let project = ($env.CURRENT_FILE | path dirname | path dirname)
  let output_dir = if $output == null { $project } else { $output | path expand }
  let source_root = ($upstream | path expand)
  let commit = (^git -C $source_root rev-parse HEAD | complete)
  if $commit.exit_code != 0 { error make {msg: $commit.stderr} }
  let pattern = '(?s)test_table!\(\s*(?<name>\w+),\s*(?<expression>.*?)\s*,\s*(?<expected>(?:"(?:\\.|[^"\\])*"\s*)+|Matrix::new\(\d+,\s*\d+\),?)\s*\);'
  for suite in [rotate reverse concat duplicate] {
    let relative = $'tabled/tests/settings/($suite)_test.rs'
    let source = (open --raw ($source_root | path join $relative))
    let cases = ($source | parse --regex $pattern)
    let count = ($source | parse --regex 'test_table!\(' | length)
    if ($cases | length) != $count {
      error make {msg: $'Failed to extract every test_table case from ($relative)'}
    }
    let body = ($cases | each {|case|
      let expression = (translate $case.expression)
      if $expression =~ 'Matrix::|\.with\(|\.into\(|let mut ' {
        error make {msg: $'Untranslated expression: ($suite)/($case.name)'}
      }
      let expected = (expected-value $case.expected)
      let actual = if ($expression | str ends-with '}') {
        $expression
      } else if ($expression | str ends-with '.to_string()') {
        $expression
      } else {
        $expression + '.to_string()'
      }
      ('///|'
      + $"\n// Upstream: ($relative)::($case.name)"
      + $"\ntest \"upstream ($suite) ($case.name)\" {\n  let actual = ($actual)\n  assert_eq\(actual, ($expected))\n}\n")
    } | str join (char nl))
    let path = ($output_dir | path join $'upstream_($suite)_test.mbt')
    let marker = '// Generated by scripts/import-transform-tests.nu.'
    if ($path | path exists) and not (open --raw $path | str starts-with $marker) {
      error make {msg: $'Refusing to overwrite a file not owned by this generator: ($path)'}
    }
    ($marker + "\n// Source revision: " + ($commit.stdout | str trim) + "\n\n" + $body)
    | save --force $path
    print $'($suite): ($count) source cases preserved'
  }
}
