#!/usr/bin/env nu
# Generate differential fixtures using upstream Rust, never MoonBit output.
use upstream-literals.nu decode-rust-string

def query [probe: path, mode: string, input: string]: nothing -> string {
  let result = ($input | ^$probe $mode | complete)
  if $result.exit_code != 0 { error make {msg: $result.stderr} }
  $result.stdout | str trim --right --char (char nl)
}

def generate [probe: path, output: path]: nothing -> nothing {
  let esc = (char -u '1b')
  let controls = [
    '' '.' '   ' " x \n y "
    $esc $'($esc)[31' $'a($esc)[31' $'($esc)[' $'($esc)]abc'
    $'($esc)[?x' $'($esc)[1;bad' $'($esc)Pstuff($esc)\x'
    $'a($esc)(char nul)b' $'($esc)($esc)[31mx' $'($esc)[0Kあ.($esc)[m'
    $'($esc)]8;;https://example.com($esc)\界($esc)]8;;($esc)\'
    $'($esc)]8;;https://example.com(char bel)link($esc)]8;;(char bel)'
    $'($esc)[31m a  ($esc)[39m  ($esc)[32m b ($esc)[0m'
    $'($esc)[31m   ($esc)[39m' $'($esc)[31m($esc)[39m'
    $"($esc)[31ma\n\nb\n($esc)[39m"
    $"($esc)[31ma\n\nb\n" $"($esc)[31m\n\n($esc)[39m"
    $'($esc)[38;5;42m😀é($esc)[0m' $'($esc)[4:3munder'
  ]
  let parameters = [
    '' '01' '1;2;3;4;5;6;7;8;9' '11;20;21;26;51;52;53;60;61;62;63;64;73;74'
    '31;42' '42;31' '31;32' '31;39' '1;22' '20;23' '31;;1' '0;999' '999;0'
    '31;999' '0;31;999' '38;2;1;2;3' '48;5;255' '58;2;8;9;10'
    '38;2;256;0;2' '38;2;1;2' '31;38;3;1' '38;5;' '38;5;0001' '38;5;+3'
    '58;5;9;59;48;2;0;8;9' '1;2;3;4;5;6;7;8;9;11;20;21;26;51;52;53;60;61;62'
    '?31;1' '>1;31' '<2;31' '31;?1' '31 m' '31  m'
    ('1;' | fill --width 66 --character '1;')
  ]
  let cases = ($controls
    | append ($parameters | each {|code| $"($esc)[($code)m x \n y ($esc)[0m" })
    | append (0..107 | each {|code| $"($esc)[($code)m x \n y ($esc)[0m" }))
  let tests = ($cases | enumerate | each {|case|
    let input = ($case.item | to json --raw)
    let width = (query $probe width $case.item | into int)
    let trimmed = (decode-rust-string (query $probe trim $case.item) | to json --raw)
    let stripped = (decode-rust-string (query $probe strip $case.item) | to json --raw)
    let lines = (query $probe split $case.item | lines | each {|line| decode-rust-string $line } | to json --raw)
    let parsed = (query $probe parse $case.item | lines)
    let color = if $parsed.0 == 'err' { 'Err(())' } else {
      let prefix = (decode-rust-string $parsed.1 | to json --raw)
      let suffix = (decode-rust-string $parsed.2 | to json --raw)
      $"Ok\(ANSIBuf::new\(($prefix), ($suffix)))"
    }
    $"///|\n// Reference: papergrid ansi feature, ansi-str 0.9.0, ansitok 0.3.0.
test \"ANSI upstream reference ($case.index)\" {
  let input = ($input)
  assert_eq\(get_line_width\(input), ($width))
  assert_eq\(strip_ansi\(input), ($stripped))
  assert_eq\(trim_ansi\(input), ($trimmed))
  assert_eq\(get_lines\(input), ($lines))
  assert_eq\(ANSIBuf::try_from\(input), ($color))
}\n"
  } | str join (char nl))
  let marker = '// Generated by scripts/import-ansi-reference-tests.nu.'
  if ($output | path exists) and not (open --raw $output | str starts-with $marker) {
    error make {msg: $'Refusing to overwrite a file not owned by this generator: ($output)'}
  }
  ($marker + "\n\n" + $tests) | save --force $output
  print $'Preserved ($cases | length) upstream ANSI reference inputs'
}

def generate-widths [probe: path, output: path]: nothing -> nothing {
  let esc = (char -u '1b')
  let link = $'($esc)]8;;https://example.com($esc)\'
  let end_link = $'($esc)]8;;($esc)\'
  let cases = [
    '' '123456' "123\n456789" "ab\n\ncd\n" '😳😳😳' '😳12😳3' '中a中'
    $'($esc)[31;100m123456($esc)[39m($esc)[49m'
    $'($esc)[31;100m😳😳😳($esc)[39m($esc)[49m'
    $'($esc)[1mab($esc)[31mcd($esc)[22mef($esc)[0m'
    $"($esc)[31mab\n\ncd\n($esc)[39m"
    $"($esc)[31mab\n\ncd\n"
    $'($esc)[31m($esc)[39m'
    $'($esc)[38;2;1;2;3mabcdef($esc)[0m'
    $'($link)abcdef($end_link)'
    $"($link)ab\ncd($end_link)"
    $'prefix($link)abcdef($end_link)suffix'
    $'($link)abc($end_link)($link)def($end_link)'
    $'($link)($esc)[31mabcdef($esc)[0m($end_link)'
    $'($esc)]8;;https://example.com(char bel)abcdef($esc)]8;;(char bel)'
    $'($esc)[2Kabcdef'
  ]
  let tests = ($cases | enumerate | each {|case|
    [0 1 2 3 4 6 10] | each {|width|
      let values = ([cut wrap] | each {|mode|
        let result = ($case.item | ^$probe $mode $width | complete)
        if $result.exit_code != 0 { error make {msg: $result.stderr} }
        decode-rust-string ($result.stdout | str trim --right --char (char nl)) | to json --raw
      })
      let input = ($case.item | to json --raw)
      $"///|\n// Reference: tabled Truncate::truncate and Wrap::wrap with ansi enabled.
test \"ANSI width reference ($case.index) at ($width)\" {
  let input = ($input)
  assert_eq\(cut_str\(input, ($width)), ($values.0))
  assert_eq\(wrap_text\(input, ($width)), ($values.1))
}\n"
    }
  } | flatten | str join (char nl))
  let marker = '// Generated by scripts/import-ansi-reference-tests.nu.'
  if ($output | path exists) and not (open --raw $output | str starts-with $marker) {
    error make {msg: $'Refusing to overwrite a file not owned by this generator: ($output)'}
  }
  ($marker + "\n\n" + $tests) | save --force $output
  print $'Preserved ($cases | length) upstream width inputs at 7 widths'
}

def main [upstream: path, --probe: path, --output: path, --width-output: path] {
  let project = ($env.CURRENT_FILE | path dirname | path dirname)
  let output = if $output == null { $project | path join papergrid/ansi_reference_test.mbt } else { $output | path expand }
  let width_output = if $width_output == null { $project | path join papergrid/ansi_width_reference_test.mbt } else { $width_output | path expand }
  if $probe != null {
    generate ($probe | path expand) $output
    generate-widths ($probe | path expand) $width_output
    return
  }
  let scratch = (mktemp --directory)
  try {
    mkdir ($scratch | path join src)
    cp ($project | path join scripts/reference/ansi_probe.rs) ($scratch | path join src/main.rs)
    {
      package: {name: 'tabular-upstream-probe', version: '0.0.0', edition: '2021'}
      dependencies: {
        papergrid: {path: ($upstream | path expand | path join papergrid), features: ['ansi']}
        ansi-str: {version: '=0.9.0'}
        ansitok: {version: '=0.3.0'}
        tabled: {path: ($upstream | path expand | path join tabled), default-features: false, features: ['std' 'ansi']}
      }
      patch: {crates-io: {papergrid: {path: ($upstream | path expand | path join papergrid)}}}
    } | to toml | save ($scratch | path join Cargo.toml)
    let result = (^cargo build --manifest-path ($scratch | path join Cargo.toml) | complete)
    if $result.exit_code != 0 { error make {msg: $result.stderr} }
    generate ($scratch | path join target/debug/tabular-upstream-probe) $output
    generate-widths ($scratch | path join target/debug/tabular-upstream-probe) $width_output
  } finally {
    # This exact directory was created by this invocation.
    rm --recursive $scratch
  }
}
