#!/usr/bin/env nu
# Preserve every fixture in papergrid's formatting configuration tests.
use upstream-literals.nu [decode-rust-string moon-string expected-lines]

def main [upstream: path, --output: path] {
  let project = ($env.CURRENT_FILE | path dirname | path dirname)
  let relative = 'papergrid/tests/grid/format_configuration.rs'
  let source = (open --raw ($upstream | path expand | path join $relative))
  let revision = (^git -C $upstream rev-parse HEAD | complete)
  if $revision.exit_code != 0 { error make {msg: $revision.stderr} }
  let variants = ($source | parse --regex '(?s)AlignmentHorizontal::(?<horizontal>\w+),\s*AlignmentVertical::(?<vertical>\w+),\s*Formatting::new\((?<formatting>[a-z, ]+)\),\s*static_table!\((?<expected>.*?)\),')
  let single = ($source | parse --regex '(?s)fn formatting_1x1_test\(\) \{(?<body>.*?)\n\}\n' | get 0.body)
  let single_expected = ($single | parse --regex '(?s)static_table!\((?<expected>.*?)\),')
  let tabs = ($source | parse --regex '(?s)fn tabs_arent_handled\(\) \{(?<body>.*)\n\}\s*$' | get 0.body)
  let tabs_expected = ($tabs | parse --regex '(?s)static_table!\((?<expected>.*?)\),' | get 0.expected)
  let static_count = ($source | parse --regex 'static_table!\(' | length)
  if ($variants | length) + ($single_expected | length) + 1 != $static_count or ($single_expected | length) != 4 {
    error make {msg: 'Failed to extract all grid formatting fixtures'}
  }
  let json = ($single | parse --regex '(?s)let json = r#"(?<text>.*?)"#;' | get 0.text)
  let tab_json = ($tabs | parse --regex '(?s)let json = (?<text>"(?:\\.|[^"\\])*");' | get 0.text | decode-rust-string $in)
  let matrix = [
    ['A long string' "\n\n\nA\n    string\nwith\n new\nline\n\n\n"]
    ['1-0' '1-1']
    ["A one more\n    string\nwith\n new\nline" '...']
  ] | to json --raw
  let variant_tests = ($variants | enumerate | each {|entry|
    let case = $entry.item
    let h = ($case.horizontal | str lowercase)
    let v = ($case.vertical | str lowercase)
    let expected = (expected-lines $case.expected)
    $"///|\n// Upstream: ($relative)::formatting_test\ntest \"upstream grid formatting variant ($entry.index)\" {
  let cfg = upstream_formatting_config\()
  cfg.set_align\(HAlign::($h)\())
  cfg.set_valign\(VAlign::($v)\())
  cfg.set_formatting\(Entity::Global, Formatting::new\(($case.formatting)))
  assert_eq\(upstream_formatting_render\(($matrix), cfg), ($expected))
}\n"
  } | str join (char nl))
  let single_tests = ($single_expected | enumerate | each {|entry|
    let i = $entry.index
    let lines = ($i > 0)
    let h = ($i > 1)
    let v = ($i > 2)
    let expected = (expected-lines $entry.item.expected)
    let text = ($json | to json --raw)
    $"///|\n// Upstream: ($relative)::formatting_1x1_test\ntest \"upstream grid formatting 1x1 ($i)\" {
  let cfg = upstream_formatting_config\()
  cfg.set_formatting\(Entity::Global, Formatting::new\(($h), ($v), ($lines)))
  assert_eq\(upstream_formatting_render\([[($text)]], cfg), ($expected))
}\n"
  } | str join (char nl))
  let tab_text = ($tab_json | to json --raw)
  let tab_expected = (expected-lines $tabs_expected)
  let extra = $"///|\n// Upstream: ($relative)::formatting_empty_test
test \"upstream grid formatting empty\" {
  for shape in [\(0, 0), \(0, 4), \(4, 0)] {
    let cfg = upstream_formatting_config\()
    cfg.set_formatting\(Entity::Global, Formatting::new\(true, true, true))
    let rows = Array::makei\(shape.0, _ => Array::make\(shape.1, \"\"))
    assert_eq\(upstream_formatting_render\(rows, cfg), \"\")
  }
}

///|\n// Upstream: ($relative)::tabs_arent_handled
test \"upstream grid tabs arent handled\" {
  assert_eq\(upstream_formatting_render\([[($tab_text)]], upstream_formatting_config\()), ($tab_expected))
}\n"
  let marker = '// Generated by scripts/import-grid-format-tests.nu.'
  let path = if $output == null { $project | path join papergrid/upstream_formatting_test.mbt } else { $output | path expand }
  if ($path | path exists) and not (open --raw $path | str starts-with $marker) {
    error make {msg: $'Refusing to overwrite a file not owned by this generator: ($path)'}
  }
  ($marker + "\n// Source revision: " + ($revision.stdout | str trim) + "\n\n" + $variant_tests + $single_tests + $extra) | save --force $path
  {source_functions: 4, matrix_variants: ($variants | length), literal_fixtures: $static_count}
}
