#!/usr/bin/env nu
# Preserve all remaining unit tests in the upstream word-wrapping implementation.
use upstream-literals.nu decode-rust-string

def main [upstream: path] {
  let project = ($env.CURRENT_FILE | path dirname | path dirname)
  let relative = 'tabled/src/settings/width/wrap.rs'
  let source = (open --raw ($upstream | path expand | path join $relative))
  let cases = ($source | parse --regex '(?ms)^    fn (?<name>\w+)\(\) \{\n(?<body>.*?)^    \}' | where name not-in [split_test chunks_test])
  if ($cases | length) != 16 { error make {msg: 'Expected all 16 remaining wrap unit tests'} }
  let body = ($cases | each {|case|
    let content = ($case.body
      | str replace --all --regex '(?m)^\s*#\[[^\n]+\]\n' ''
      | str replace --all --regex '(?m)^\s*let (?:split|split_keeping_words) =[^\n]+\n' ''
      | str replace --all 'use ansi_str::AnsiStr;' ''
      | str replace --all 'assert_eq!(' 'assert_eq('
      | str replace --all --regex '\b(split|split_keeping_words)\(' 'upstream_wrap_words('
      | str replace --all 'wrap_text_basic(' 'wrap_basic('
      | str replace --all 'wrap_text_keeping_words(' 'wrap_words('
      | str replace --all --regex '(?s)\.ansi_split\("\\n"\)\s*\.collect::<Vec<_>>\(\)' '.upstream_ansi_lines()'
      | str replace --all '["^$"; 0]' 'Array::make(0, "^$")'
      | str replace --all --regex '(?s)concat!\((?<parts>(?:\s*"(?:\\.|[^"\\])*"\s*,?)+)\s*\)' {|parts| '[' + $parts + '].join("")' }
      | str replace --all --regex '(?m);[ \t]*$' ''
      | str replace --all --regex '(?s)("(?:\\.|[^"\\])*")' {|literal| decode-rust-string $literal | to json --raw }
      | str trim)
    $"///|\n// Upstream: ($relative)::($case.name)
test \"upstream wrap unit ($case.name)\" {
  ($content)
}\n"
  } | str join (char nl))
  let marker = '// Generated by scripts/import-wrap-tests.nu.'
  let output = ($project | path join papergrid/upstream_wrap_wbtest.mbt)
  if ($output | path exists) and not (open --raw $output | str starts-with $marker) { error make {msg: 'Output is not owned by this generator'} }
  ($marker + "\n\n" + $body) | save --force $output
  print $'Preserved ($cases | length) remaining wrap unit tests'
}
