#!/usr/bin/env nu
# Generate height state assertions from the local Rust implementation.
use upstream-literals.nu decode-rust-string
use import-transform-tests.nu translate

def generate [probe: path, source: path, output: path] {
  let cases = (open --raw $source | parse --regex '"(?<name>[a-z-]+)" => \{ (?<action>[^\n]+) \},')
  if ($cases | length) != 37 { error make {msg: 'Expected all 37 reference scenarios'} }
  let tests = ($cases | each {|case|
    let result = (^$probe $case.name | complete)
    if $result.exit_code != 0 { error make {msg: $'Reference failed for ($case.name): ($result.stderr)'} }
    let parts = ($result.stdout | lines)
    if ($parts | length) != 8 { error make {msg: $'Unexpected probe response for ($case.name)'} }
    let rendered = (decode-rust-string $parts.0 | to json --raw)
    let records = ($parts | skip 5 | each {|row|
      $row | parse --regex '("(?:\\.|[^"\\])*")' | get capture0 | each {|literal| decode-rust-string $literal }
    } | to json --raw)
    let action = ($case.action
      | str replace --all '.with(MeasuredCells(true))' '.modify(Segment::all(), Height::increase(Max))'
      | str replace --all '.with(MeasuredCells(false))' '.modify(Segment::all(), Height::limit(Min))'
      | str replace --all --regex '"(?:\\.|[^"\\])*"' { decode-rust-string $in | to json --raw }
      | str replace --all 'vec![' '['
      | str replace --all --regex '\b(Max|Min)\)' '@tabular.$1::new())'
      | str replace --all 'Percent(' '@tabular.Percent::new(')
    let action = (translate $action
      | str replace --all --regex '(?<![\w.])(Height|Width|PriorityMin|PriorityMax|Margin)::' '@tabular.$1::'
      | str trim --right --char ';')
    $"///|\n// Reference: tabled height options, original records and observable cache state.
test \"height state reference ($case.name)\" {
  let table = @tabular.Table::from_rows\([[\"a\\nb\\nc\\n\", \"long value\"], [\"d\\ne\", \"x\\ny\\nz\"], [\"\", \"q\"]])
  ($action) |> ignore
  assert_eq\(table.to_string\(), ($rendered))
  assert_eq\(table.get_dimension\().get_widths\(), ($parts.1))
  assert_eq\(table.get_dimension\().get_heights\(), ($parts.2))
  assert_eq\(table.total_width\(), ($parts.3))
  assert_eq\(table.total_height\(), ($parts.4))
  assert_eq\(table.rows, ($records))
}\n"
  } | str join (char nl))
  let marker = '// Generated by scripts/import-height-state-tests.nu.'
  if ($output | path exists) and not (open --raw $output | str starts-with $marker) { error make {msg: 'Output is not owned by this generator'} }
  ($marker + "\n\n" + $tests) | save --force $output
  print $'Compared ($cases | length) upstream height state scenarios'
}

def main [upstream: path, --probe: path, --output: path] {
  let project = ($env.CURRENT_FILE | path dirname | path dirname)
  let output = if $output == null { $project | path join height_state_reference_test.mbt } else { $output | path expand }
  let source = ($project | path join scripts/reference/height_state_probe.rs)
  if $probe != null { generate ($probe | path expand) $source $output; return }
  let scratch = (mktemp --directory)
  try {
    mkdir ($scratch | path join src)
    cp $source ($scratch | path join src/main.rs)
    {
      package: {name: 'tabular-height-state-probe', version: '0.0.0', edition: '2021'}
      dependencies: {tabled: {path: ($upstream | path expand | path join tabled), default-features: false, features: [std ansi]}}
      patch: {crates-io: {papergrid: {path: ($upstream | path expand | path join papergrid)}}}
    } | to toml | save ($scratch | path join Cargo.toml)
    let result = (^cargo build --manifest-path ($scratch | path join Cargo.toml) | complete)
    if $result.exit_code != 0 { error make {msg: $result.stderr} }
    generate ($scratch | path join target/debug/tabular-height-state-probe) $source $output
  } finally {
    rm --recursive $scratch
  }
}
