#!/usr/bin/env nu
# Preserve all padding/margin source cases and the upstream ignored status.
use upstream-literals.nu [expected-lines decode-rust-string]
use import-transform-tests.nu translate
use api-names.nu modernize-api

def indent-expression [expression: string]: nothing -> string {
  let input = ($expression
    | str replace --all 'Highlight::outline(Cell::' 'Highlight::outline_cell(Cell::'
    | str replace --all --regex 'assert_width!\((\w+),\s*(\d+)\);' 'upstream_assert_width($1, $2)'
    | str replace --all 'use tabled::settings::Color;' '')
  translate $input
    | str replace --all 'assert_eq!(' 'assert_eq('
    | str replace --all --regex '(?<![\w.])(PaddingColor|MarginColor|Margin|Highlight|Width)::' '@tabular.$1::'
}

def main [upstream: path, --output: path] {
  let project = ($env.CURRENT_FILE | path dirname | path dirname)
  let output = if $output == null { $project } else { $output | path expand }
  let macro_pattern = '(?s)test_table!\(\s*(?<name>\w+),\s*(?<expression>.*?)\s*,\s*(?<expected>(?:"(?:\\.|[^"\\])*"\s*)+)\s*\);'
  for suite in [padding margin] {
    let relative = $'tabled/tests/settings/($suite)_test.rs'
    let source = (open --raw ($upstream | path expand | path join $relative))
    let cases = ($source | parse --regex $macro_pattern)
    let count = ($source | parse --regex 'test_table!\(' | length)
    if ($cases | length) != $count { error make {msg: $'Failed to extract every case from ($relative)'} }
    let macros = ($cases | each {|case|
      let expression = (indent-expression $case.expression)
      let expected = (expected-lines $case.expected)
      $"///|\n// Upstream: ($relative)::($case.name)
test \"upstream ($suite) ($case.name)\" {
  let actual = ($expression).to_string\()
  assert_eq\(actual, ($expected))
}\n"
    } | str join (char nl))
    let functions = ($source | parse --regex '(?s)(?:#\[ignore = "(?<reason>[^"]+)"\]\s*)?fn (?<name>\w+)\(\) \{(?<body>.*?)\n\}')
    let ordinary = ($functions | each {|case|
      let body = ($case.body
        | str replace --all --regex '(?s)assert_table!\(\s*table,\s*((?:"(?:\\.|[^"\\])*"\s*)+)\s*\);' {|literals|
          'assert_eq(table, ' + (expected-lines $literals) + ')'
        })
      let body = (indent-expression $body)
      let skip = if ($case.reason | is-empty) { '' } else { '#skip(' + ($case.reason | to json --raw) + ')' + (char nl) }
      $"///|\n// Upstream: ($relative)::($case.name)
($skip)test \"upstream ($suite) ($case.name)\" {
  ($body)
}\n"
    } | str join (char nl))
    let expected_count = if $suite == 'padding' { 7 } else { 8 }
    if (($cases | length) + ($functions | length)) != $expected_count { error make {msg: $'Unexpected ($suite) source count'} }
    let path = ($output | path join $'upstream_($suite)_test.mbt')
    let marker = '// Generated by scripts/import-indent-tests.nu.'
    if ($path | path exists) and not (open --raw $path | str starts-with $marker) { error make {msg: $'Output not owned by generator: ($path)'} }
    ($marker + "\n\n" + $macros + $ordinary) | save --force $path
    print $'($suite): ($expected_count) original tests preserved'
  }
  let relative = 'papergrid/tests/grid/settings.rs'
  let source = (open --raw ($upstream | path expand | path join $relative))
  let cases = ($source | parse --regex $macro_pattern | where name =~ '^entity_(?:row|column)_overrides_')
  if ($cases | length) != 4 { error make {msg: 'Expected four source padding override cases'} }
  let body = ($cases | each {|case|
    let config = ($case.expression | parse --regex '(?s)\.config\(\|cfg\| \{(?<config>.*?)\}\)' | get 0.config
      | str replace --all 'Borders::default()' 'Borders::empty()'
      | str replace --all '.set_padding(' '.set_padding_sides('
      | str replace --all --regex '(?s)Sides \{\s*bottom: (Indent::new\([^)]*\)),\s*\.\.Default::default\(\)\s*\}' '{ ..Sides::default(), bottom: $1 }'
      | str replace --all --regex ';(?=\s*(?:\n|$))' ''
      | modernize-api)
    let expected = (expected-lines $case.expected)
    $"///|\n// Upstream: ($relative)::($case.name)
test \"upstream padding scope ($case.name)\" {
  let cfg = upstream_formatting_config\()
  ($config)
  assert_eq\(upstream_formatting_render\([[\"0-0\", \"0-1\"], [\"1-0\", \"1-1\"]], cfg), ($expected))
}\n"
  } | str join (char nl))
  let path = ($output | path join papergrid/upstream_indent_config_test.mbt)
  let marker = '// Generated by scripts/import-indent-tests.nu.'
  if ($path | path exists) and not (open --raw $path | str starts-with $marker) { error make {msg: $'Output not owned by generator: ($path)'} }
  ($marker + "\n\n" + $body) | save --force $path
  print 'papergrid: preserved four original padding scope cases'
}
