#!/usr/bin/env nu
use upstream-probe.nu build-upstream-probe
# Compare rendered output, records, dimensions, and actual expanded padding.
use upstream-literals.nu decode-rust-string
use import-transform-tests.nu translate

def generate [probe: path, source: path, output: path] {
  let cases = (open --raw $source | parse --regex '"(?<name>[a-z-]+)" => \{ (?<action>[^\n]+) \},')
  if ($cases | length) != 32 { error make {msg: 'Expected all 32 indent scenarios'} }
  let tests = ($cases | each {|case|
    let result = (^$probe $case.name | complete)
    if $result.exit_code != 0 { error make {msg: $'Reference failed for ($case.name): ($result.stderr)'} }
    let parts = ($result.stdout | lines)
    if ($parts | length) != 9 { error make {msg: $'Unexpected probe response for ($case.name)'} }
    let rendered = (decode-rust-string $parts.0 | to json --raw)
    let records = ($parts | skip 5 | take 3 | each {|row|
      $row | parse --regex '("(?:\\.|[^"\\])*")' | get capture0 | each {|literal| decode-rust-string $literal }
    } | to json --raw)
    let action = (translate $case.action
      | str replace --all '.get_config_mut()' '.config'
      | str replace --all '.set_margin_offset(' '.set_margin_offsets('
      | str replace --all --regex '(?<![\w.])(Height|Width|PaddingColor|MarginColor|Margin|Sides|Offset)::' '@tabular.$1::'
      | str replace --all '; table.' " |> ignore\n  table."
      | str trim --right --char ';')
    let end = if ($action | str contains '.set_margin_offsets(') { '' } else { ' |> ignore' }
    $"///|\n// Reference: upstream padding expansion, colors, scopes, and margin offsets.
test \"indent state reference ($case.name)\" {
  let table = @tabular.Table::from_rows\([[\"a\\nb\", \"long value\"], [\"d\", \"x\\ny\\nz\"], [\"\", \"q\"]])
  ($action)($end)
  assert_eq\(table.to_string\(), ($rendered))
  assert_eq\(table.get_dimension\().get_widths\(), ($parts.1))
  assert_eq\(table.get_dimension\().get_heights\(), ($parts.2))
  assert_eq\(table.total_width\(), ($parts.3))
  assert_eq\(table.total_height\(), ($parts.4))
  assert_eq\(table.rows, ($records))
  let padding = Array::makei\(6, index => {
    let pad = table.config.get_padding\(index / 2, index % 2)
    [pad.left.size, pad.right.size, pad.top.size, pad.bottom.size]
  })
  assert_eq\(padding, ($parts.8))
}\n"
  } | str join (char nl))
  let marker = '// Generated by scripts/import-indent-state-tests.nu.'
  if ($output | path exists) and not (open --raw $output | str starts-with $marker) { error make {msg: 'Output is not owned by this generator'} }
  ($marker + "\n\n" + $tests) | save --force $output
  print $'Compared ($cases | length) upstream indent scenarios'
}

def main [upstream: path, --probe: path, --output: path] {
  let project = ($env.CURRENT_FILE | path dirname | path dirname)
  let output = if $output == null { $project | path join indent_state_reference_test.mbt } else { $output | path expand }
  let source = ($project | path join scripts/reference/indent_state_probe.rs)
  if $probe != null { generate ($probe | path expand) $source $output; return }
  let scratch = (mktemp --directory)
  try {
    let binary = (build-upstream-probe $upstream ($project | path join scripts/reference/indent_state_probe.rs) $scratch)
    generate $binary $source $output
  } finally {
    rm --recursive $scratch
  }
}
