#!/usr/bin/env nu
# Preserve the upstream literal expectations for string cutting and wrapping.
use upstream-literals.nu decode-rust-string

def main [upstream: path] {
  let root = ($upstream | path expand)
  let project = ($env.CURRENT_FILE | path dirname | path dirname)
  let cases = [
    {source: 'tabled/src/util/string.rs', name: 'strip_test'}
    {source: 'tabled/src/util/string.rs', name: 'strip_color_test'}
    {source: 'tabled/src/util/string.rs', name: 'test_color_strip'}
    {source: 'tabled/src/settings/width/wrap.rs', name: 'split_test'}
    {source: 'tabled/src/settings/width/wrap.rs', name: 'chunks_test'}
  ]
  let tests = ($cases | each {|case|
    let source = (open --raw ($root | path join $case.source))
    let pattern = '(?ms)^    fn ' + $case.name + '\(\) \{\n(?<body>.*?)^    \}'
    let matches = ($source | parse --regex $pattern)
    if ($matches | length) != 1 { error make {msg: $'Expected exactly one ($case.name)'} }
    let raw = if $case.name in [split_test chunks_test] {
      $matches.0.body | str replace --regex '(?s)^.*?(?=assert_eq!)' ''
    } else { $matches.0.body }
    let body = ($raw
      | str replace --all 'assert_eq!(' 'assert_eq('
      | str replace --all --regex '\b(split|chunks)\(' 'wrap_text('
      | str replace --all --regex '(?m);[ \t]*$' ''
      | str replace --all --regex '("(?:\\.|[^"\\])*")' {|literal| decode-rust-string $literal | to json --raw }
      | str trim)
    $"///|\n// Upstream: ($case.source)::($case.name)
test \"upstream string ($case.name)\" {
  ($body)
}\n"
  } | str join (char nl))
  let marker = '// Generated by scripts/import-string-tests.nu.'
  let output = ($project | path join papergrid/upstream_string_test.mbt)
  if ($output | path exists) and not (open --raw $output | str starts-with $marker) {
    error make {msg: $'Refusing to overwrite a file not owned by this generator: ($output)'}
  }
  ($marker + "\n\n" + $tests) | save --force $output
  print $'Preserved ($cases | length) upstream string tests'
}
