# Description:
#   - Tabular build & test Check

name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

    paths-ignore:
      - '**.md'

jobs:
  tabular-check:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        # os: [windows-latest, ubuntu-latest, macos-latest, macos-15-intel]
    runs-on: ${{ matrix.os }}
    name: Setup MoonBit@${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Moonbit
        uses: hustcer/setup-moonbit@main

      - name: Check Tabular Build & Test
        run: |
          moon version --all
          moon check --target all
          moon build --target all
          moon test --target all

