# Description:
#   - Tabular build & test Check

name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  tabular-check:
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        # os: [windows-latest, ubuntu-latest, macos-latest, macos-15-intel]
    runs-on: ${{ matrix.os }}
    name: Setup MoonBit@${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Moonbit
        uses: hustcer/setup-moonbit@main

      - name: Check Tabular Build & Test
        run: |
          moon version --all
          moon fmt --check
          moon check --target all --deny-warn
          moon build --target all --deny-warn
          moon test --target all --deny-warn
      - name: Check Generated Interfaces
        run: |
          moon info
          git diff --exit-code -- '*.mbti'
